export const interns = [
  {
    name: "Fredrick Michael",
    img: "./user-1.png",
    track: "Frontend",
    grade: "98",
  },
  {
    name: "Helen Paul",
    img: "./user-2.png",
    track: "Frontend",
    grade: "67",
  },
  {
    name: "Peter Sunday",
    img: "./user-3.png",
    track: "Backend",
    grade: "86",
  },
  {
    name: "Tonia Philip",
    img: "./user-4.png",
    track: "Frontend",
    grade: "83",
  },
  {
    name: "Darlington Smith",
    img: "./user-5.png",
    track: "Backend",
    grade: "57",
  },
  {
    name: "Tom Shank",
    img: "./user-1.png",
    track: "Backend",
    grade: "59",
  },
  {
    name: "Ada Thomas",
    img: "./user-2.png",
    track: "Product Design",
    grade: "79",
  },
  {
    name: "Angel Peter",
    img: "./user-3.png",
    track: "Web 3",
    grade: "94",
  },
  {
    name: "Peter Wills",
    img: "./user-4.png",
    track: "Product Design",
    grade: "80",
  },
  {
    name: "Henry Scot",
    img: "./user-5.png",
    track: "Web 3",
    grade: "68",
  },
  {
    name: "Jerry Hall",
    img: "./user-1.png",
    track: "Frontend",
    grade: "39",
  },
  {
    name: "Thomas Lah",
    img: "./user-2.png",
    track: "Product Design",
    grade: "89",
  },
  {
    name: "Kelvin Law",
    img: "./user-3.png",
    track: "Web 3",
    grade: "67",
  },
  {
    name: "Wright Wills",
    img: "./user-4.png",
    track: "Frontend",
    grade: "50",
  },
  {
    name: "Henry Stones",
    img: "./user-5.png",
    track: "Backend",
    grade: "87",
  },
  {
    name: "Anthony Mark",
    img: "./user-1.png",
    track: "Backend",
    grade: "69",
  },
  {
    name: "Henry Danger",
    img: "./user-2.png",
    track: "Product Design",
    grade: "59",
  },
  {
    name: "Sean Paul",
    img: "./user-3.png",
    track: "Web 3",
    grade: "47",
  },
  {
    name: "Solomon Hays",
    img: "./user-4.png",
    track: "Product Design",
    grade: "30",
  },
  {
    name: "Emmanuel Hills",
    img: "./user-5.png",
    track: "Web 3",
    grade: "62",
  },
];
